## Numpy ile 2 bilinmeyenli denklem çözme

In [2]:
import numpy as np

5 * x0 + x1 = 12
x0 + 3 + x1 = 10

In [4]:
## 1. denklemin kat sayisi 5, gizli 1 
## 2. denklemin kat sayisi 1, 2. bilinmeyen kat sayi 3
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [5]:
a

array([[5, 1],
       [1, 3]])

In [6]:
b

array([12, 10])

In [7]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])