## alt küme üzerinde işlem yapmak

In [1]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[3, 4, 8, 7, 9],
       [5, 2, 2, 1, 2],
       [6, 2, 3, 6, 8],
       [2, 6, 5, 7, 9],
       [6, 1, 4, 1, 2]])

In [2]:
alt_a = a[0:3, 0:2]
alt_a

array([[3, 4],
       [5, 2],
       [6, 2]])

In [5]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [6]:
alt_a

array([[99999,     4],
       [    5,   888],
       [    6,     2]])

In [7]:
a

array([[99999,     4,     8,     7,     9],
       [    5,   888,     2,     1,     2],
       [    6,     2,     3,     6,     8],
       [    2,     6,     5,     7,     9],
       [    6,     1,     4,     1,     2]])

In [8]:
# yukardaki işlem ana array bozuluyor dikkat etmek gerek.

In [9]:
m = np.random.randint(10, size = (5,5))
m

array([[0, 2, 9, 9, 6],
       [9, 1, 5, 1, 8],
       [1, 8, 4, 4, 8],
       [1, 1, 8, 9, 3],
       [9, 1, 1, 3, 2]])

In [11]:
# copy ile ana array'den bağımsız oldu. 
alt_b = m[0:3, 0:2].copy()

In [12]:
alt_b

array([[0, 2],
       [9, 1],
       [1, 8]])

In [13]:
alt_b[0,0]

0

In [14]:
alt_b[0,0] = 999

In [15]:
alt_b

array([[999,   2],
       [  9,   1],
       [  1,   8]])

In [16]:
m

array([[0, 2, 9, 9, 6],
       [9, 1, 5, 1, 8],
       [1, 8, 4, 4, 8],
       [1, 1, 8, 9, 3],
       [9, 1, 1, 3, 2]])

In [18]:
# görüldüğü üzere ana array bozulmadı.