## Array Birleştirme (Concatenation)

In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [5]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [6]:
z = np.array([7,8,9])

In [7]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## iki boyuta nasıl alacağız?

In [8]:
a = np.array([[1,2,3],
              [4,5,6]])

In [9]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
# axis = 0 : satır bazında yaptı
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [14]:
# axis = 1 : sütün bazında yaptı
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])