In [1]:
## Fancy Index ile Elemanlara Erişmek

In [2]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
# Fancy : Fantastik, büyüleyici anlamında..

In [5]:
v[1]

3

In [6]:
v[3]

9

In [7]:
v[5]

15

In [9]:
# değerleri bir arada görmek istersek
[v[1],v[3],v[5]]

[3, 9, 15]

In [10]:
al_getir = [1,3,5]

In [11]:
## fancy index buna deniyor.
v[al_getir]

array([ 3,  9, 15])

## İki Boyutta Fancy

In [12]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [14]:
m[satir, sutun]

array([1, 5])

In [15]:
# basit index ile fancy index

In [16]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# basit index ve fancy index kullanılıyor.
m[[0], [1,2]] 

array([1, 2])

In [19]:
# slice ile fancy kullanımı
m[0:, [1,2]] 

array([[1, 2],
       [4, 5],
       [7, 8]])