## indeks ile elemanlar erişmek

In [1]:
import numpy as np
a = np.random.randint(10,size=10)
a

array([9, 4, 1, 1, 0, 2, 2, 4, 4, 3])

In [2]:
a[0]

9

In [3]:
a[-1]

3

In [4]:
a[0] = 100

In [5]:
a

array([100,   4,   1,   1,   0,   2,   2,   4,   4,   3])

In [6]:
m = np.random.randint(10,size=(3,5))
m

array([[1, 6, 8, 7, 7],
       [3, 3, 5, 4, 7],
       [7, 1, 0, 4, 6]])

In [7]:
m[0,0]

1

In [8]:
m[1,1]

3

In [9]:
m[1,2]

5

In [10]:
m[1,2] = 99 
m

array([[ 1,  6,  8,  7,  7],
       [ 3,  3, 99,  4,  7],
       [ 7,  1,  0,  4,  6]])

In [11]:
m[1,4] = 2.2

In [12]:
m

array([[ 1,  6,  8,  7,  7],
       [ 3,  3, 99,  4,  2],
       [ 7,  1,  0,  4,  6]])

In [13]:
# yukarıda 2.2 ondalikli değeri atadık burada dikkat ettiyse 2 olarak atadı
# yani array hangi tipteyse int,float o şekilde atamayı yapıyor.