In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14,4,2,13], dtype="float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [8]:
np.array([3.14,4,2,13], dtype="int")

array([ 3,  4,  2, 13])

In [9]:
# sifirdan array oluşturma 

In [11]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [16]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [17]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
np.random.normal(10,4, (3,4))

array([[12.84024062, 11.25203567, 13.10405446, 14.52349041],
       [16.45093832,  2.75983151, 15.08696299,  6.4338406 ],
       [ 9.22094502, 12.08759222, 12.94958801, 14.19320351]])

In [19]:
np.random.randint(0,10, (3,3))

array([[4, 5, 4],
       [9, 5, 2],
       [5, 5, 9]])