## Array Sıralama (sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,5,3,4])

In [3]:
v

array([2, 1, 5, 3, 4])

In [6]:
# bu yapı array yapısını bozmadan sıralar.
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 5, 3, 4])

In [7]:
# bu yapıysa arrayı sıralar ve yapı bozulur
v.sort()

In [8]:
v

array([1, 2, 3, 4, 5])

## iki boyutlu sıralama

In [9]:
m = np.random.normal(20,5,(3,3))

In [10]:
m

array([[18.12485982, 15.07300596, 21.86376756],
       [20.75751106, 21.51132358, 18.25191553],
       [29.44413334, 14.38774976, 14.9692384 ]])

In [11]:
# 2 boyutlu arrayin satırlarını sıralamak istiyoruz

np.sort(m, axis=1)

array([[15.07300596, 18.12485982, 21.86376756],
       [18.25191553, 20.75751106, 21.51132358],
       [14.38774976, 14.9692384 , 29.44413334]])

In [12]:
# 2 boyutlu arrayin sutünları sıralamak istiyoruz

np.sort(m, axis=0)

array([[18.12485982, 14.38774976, 14.9692384 ],
       [20.75751106, 15.07300596, 18.25191553],
       [29.44413334, 21.51132358, 21.86376756]])