## Slicing ile Elemanlara Erişmek (Array alt kümesine Erişmek)

In [1]:
import numpy as np

In [3]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]

array([20, 21, 22])

In [5]:
a[:3]

array([20, 21, 22])

In [6]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [8]:
a[1::2]
# 1 elemandan başlayarak 2 şer 2 şer atlayarak yaz

array([21, 23, 25, 27, 29])

In [9]:
a[0::2]

array([20, 22, 24, 26, 28])

In [10]:
a[2::2]

array([22, 24, 26, 28])

In [11]:
a[0::3]

array([20, 23, 26, 29])

In [12]:
## iki boyulu slice işlemleri

In [13]:
m = np.random.randint(10,size=(5,5))

In [14]:
m

array([[9, 3, 0, 7, 3],
       [1, 9, 6, 9, 9],
       [6, 8, 9, 1, 0],
       [7, 3, 9, 1, 3],
       [8, 9, 4, 6, 7]])

In [16]:
# bütün satırları seç. ilk sütüna eriş
m[:,0]

array([9, 1, 6, 7, 8])

In [17]:
m[:,1]

array([3, 9, 8, 3, 9])

In [18]:
# ilk satırı çekmek için
m[0,:]

array([9, 3, 0, 7, 3])

In [19]:
# ilk satırı çekmek için
m[0]

array([9, 3, 0, 7, 3])

In [20]:
# ilk sütünü çekmek için
m[1,:]

array([1, 9, 6, 9, 9])

In [22]:
# satır ve sütünları kesme, getirme işlemi
m[0:2, 0:3]

array([[9, 3, 0],
       [1, 9, 6]])

In [24]:
# tüm sütünları al :: demek.
m[::,:2]

array([[9, 3],
       [1, 9],
       [6, 8],
       [7, 3],
       [8, 9]])

In [25]:
# bir diğer kullanımı
m[:,0:2]

array([[9, 3],
       [1, 9],
       [6, 8],
       [7, 3],
       [8, 9]])

In [27]:
# 1 ve 3 arasındaki satırlar sonrasında ilk 2 sütün alınır
m[1:3,0:2]

array([[1, 9],
       [6, 8]])